#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# check for pishrink running and exit if so.
if ! /opt/avnet-iot/iotservices/checkpishrink; then
    echo -e "\e[31mPiShrink Running delaying BOOT service"
    exit 1
fi
echo "Starting Smartedge-iiot-gateway BOOT service"

systemctl disable wpa_supplicant.service
systemctl stop wpa_supplicant.service
rm /etc/wpa_supplicant/wpa_supplicant.conf
/opt/avnet-iot/iotservices/iotsetup
systemctl enable hostapd
systemctl enable dnsmasq
systemctl start dnsmasq
systemctl start hostapd
systemctl enable ledservice
systemctl restart ledservice
systemctl disable bootservice
