#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# check for pishrink running and exit if so.
if ! /opt/avnet-iot/iotservices/checkpishrink; then
    echo -e "\e[31mPiShrink Running delaying Button service"
    exit 1
fi

echo "Starting Smartedge-iiot-gateway Button service"
rmmod attiny_btn
modprobe attiny_btn

# wait for device
while [ ! -c /dev/button ];
do
    sleep 2
    echo "waiting for button device"
done
# wait for device
while [ ! -c /dev/reset ];
do
    sleep 2
    echo "waiting for reset device"
done
# wait for device
while [ ! -c /dev/factoryreset ];
do
    sleep 2
    echo "waiting for factoryreset device"
done

/opt/avnet-iot/iotservices/stopwd
python -u /opt/avnet-iot/iotservices/button.py >>/var/log/button.log 2>&1
echo "Button python restart" >>/var/log/button.log
