#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# check for pishrink running and exit if so.
if ! /opt/avnet-iot/iotservices/checkpishrink; then
    echo -e "\e[31mPiShrink Running delaying LED service"
    exit 1
fi

echo "Starting Smartedge-iiot-gateway ConfigurationMode LED service"
#wait for device
while [ ! -d /sys/class/leds/green ];
do
    sleep 2
    echo "waiting for green brightness system device"
done
# wait for device
while [ ! -d /sys/class/leds/red ];
do
    sleep 2
    echo "waiting for red brightness system device"
done
# wait for device
while [ ! -d /sys/class/leds/smartedge_led_duty ];
do
    sleep 2
    echo "waiting for smartedge_led_duty system device"
done

/opt/avnet-iot/iotservices/stopwd
python -u /opt/avnet-iot/iotservices/led.py >/dev/null
echo "Led python restart" >>/var/log/led.log
