#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

while [ ! -c /dev/watchdog1 ];
do
    sleep 1
    echo 'waiting for watchdog'
done
echo V > /dev/watchdog1
systemctl enable smartedgehalt
