#!/bin/bash
## Perform reset into WiFi/AP mode and start REST API

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

if [[ "$1" == "soft" ]]; then
  # Enable WiFi/AP mode and start REST API (system will be in an odd mode)
  ifconfig wlan0 down
  #systemctl disable wpa_supplicant.service
  systemctl stop wpa_supplicant.service
  rm /etc/wpa_supplicant/wpa_supplicant.conf
  cp /etc/default/hostapd.ap /etc/default/hostapd
  cp /etc/dhcpcd.conf.ap /etc/dhcpcd.conf
  cp /etc/dnsmasq.conf.ap /etc/dnsmasq.conf
  ifconfig wlan0 up
  systemctl restart dhcpcd
  systemctl restart dnsmasq
  systemctl restart hostapd
  #systemctl enable restservice
  systemctl start restservice
  #systemctl start ledservice
else
  # Revert to Configuration mode
  ifconfig wlan0 down
  systemctl disable wpa_supplicant.service
  systemctl stop wpa_supplicant.service
  rm /etc/wpa_supplicant/wpa_supplicant.conf
  cp /etc/default/hostapd.ap /etc/default/hostapd
  cp /etc/dhcpcd.conf.ap /etc/dhcpcd.conf
  cp /etc/dnsmasq.conf.ap /etc/dnsmasq.conf
  ifconfig wlan0 up
  systemctl enable dhcpcd
  systemctl enable dnsmasq
  systemctl enable hostapd
  systemctl restart dhcpcd
  systemctl restart dnsmasq
  systemctl restart hostapd
  systemctl enable restservice
  systemctl start restservice
  systemctl enable ledservice
  systemctl start ledservice
  systemctl disable iotconnectservice
  /sbin/reboot
fi
