#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# Put dummy one in so that we can truely exit AP mode, odd bug
cp /etc/wpa_supplicant/wpa_supplicant.default /etc/wpa_supplicant/wpa_supplicant.conf

# start client mode
/opt/avnet-iot/iotservices/wifi_client
